// Mocks generated by Mockito 5.3.2 from annotations
// in lift_to_live_flutter/test/presenter_tests/log_in_page_presenter_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;

import 'package:lift_to_live_flutter/domain/entities/image.dart' as _i3;
import 'package:lift_to_live_flutter/domain/entities/role.dart' as _i8;
import 'package:lift_to_live_flutter/domain/entities/user.dart' as _i2;
import 'package:lift_to_live_flutter/domain/repositories/token_repo.dart'
    as _i5;
import 'package:lift_to_live_flutter/domain/repositories/user_repo.dart' as _i7;
import 'package:lift_to_live_flutter/presentation/views/log_in_form_view.dart'
    as _i4;
import 'package:lift_to_live_flutter/presentation/views/log_in_page_view.dart'
    as _i9;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeUser_0 extends _i1.SmartFake implements _i2.User {
  _FakeUser_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeMyImage_1 extends _i1.SmartFake implements _i3.MyImage {
  _FakeMyImage_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeLogInFormView_2 extends _i1.SmartFake implements _i4.LogInFormView {
  _FakeLogInFormView_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [TokenRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockTokenRepository extends _i1.Mock implements _i5.TokenRepository {
  MockTokenRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<String> getToken(
    String? email,
    String? password,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getToken,
          [
            email,
            password,
          ],
        ),
        returnValue: _i6.Future<String>.value(''),
      ) as _i6.Future<String>);
}

/// A class which mocks [UserRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockUserRepository extends _i1.Mock implements _i7.UserRepository {
  MockUserRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<List<_i8.Role>> fetchUserRoles(String? jwtToken) =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchUserRoles,
          [jwtToken],
        ),
        returnValue: _i6.Future<List<_i8.Role>>.value(<_i8.Role>[]),
      ) as _i6.Future<List<_i8.Role>>);
  @override
  _i6.Future<_i2.User> fetchUser(
    String? userId,
    String? jwtToken,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchUser,
          [
            userId,
            jwtToken,
          ],
        ),
        returnValue: _i6.Future<_i2.User>.value(_FakeUser_0(
          this,
          Invocation.method(
            #fetchUser,
            [
              userId,
              jwtToken,
            ],
          ),
        )),
      ) as _i6.Future<_i2.User>);
  @override
  _i6.Future<List<_i2.User>> fetchMyTrainees(
    String? userId,
    String? jwtToken,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchMyTrainees,
          [
            userId,
            jwtToken,
          ],
        ),
        returnValue: _i6.Future<List<_i2.User>>.value(<_i2.User>[]),
      ) as _i6.Future<List<_i2.User>>);
  @override
  _i6.Future<List<_i3.MyImage>> fetchUserImages(
    String? userId,
    String? jwtToken,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getUserImages,
          [
            userId,
            jwtToken,
          ],
        ),
        returnValue: _i6.Future<List<_i3.MyImage>>.value(<_i3.MyImage>[]),
      ) as _i6.Future<List<_i3.MyImage>>);
  @override
  _i6.Future<_i3.MyImage> fetchProfileImage(
    String? userId,
    String? jwtToken,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchProfileImage,
          [
            userId,
            jwtToken,
          ],
        ),
        returnValue: _i6.Future<_i3.MyImage>.value(_FakeMyImage_1(
          this,
          Invocation.method(
            #fetchProfileImage,
            [
              userId,
              jwtToken,
            ],
          ),
        )),
      ) as _i6.Future<_i3.MyImage>);
  @override
  _i6.Future<void> patchImage(
    int? id,
    String? userId,
    String? date,
    String? encoded,
    String? type,
    String? jwtToken,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #patchImage,
          [
            id,
            userId,
            date,
            encoded,
            type,
            jwtToken,
          ],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);
  @override
  _i6.Future<void> postImage(
    String? userId,
    String? date,
    String? encoded,
    String? type,
    String? jwtToken,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #postImage,
          [
            userId,
            date,
            encoded,
            type,
            jwtToken,
          ],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);
  @override
  _i6.Future<void> deleteImage(
    int? id,
    String? jwtToken,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteImage,
          [
            id,
            jwtToken,
          ],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);
  @override
  _i6.Future<List<_i8.Role>> fetchCoachRoles(String? jwtToken) =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchCoachRoles,
          [jwtToken],
        ),
        returnValue: _i6.Future<List<_i8.Role>>.value(<_i8.Role>[]),
      ) as _i6.Future<List<_i8.Role>>);
  @override
  _i6.Future<void> registerUser(
    String? userId,
    String? coachId,
    String? password,
    String? name,
    String? phoneNumber,
    String? nationality,
    String? dateOfBirth,
    String? jwtToken,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #registerUser,
          [
            userId,
            coachId,
            password,
            name,
            phoneNumber,
            nationality,
            dateOfBirth,
            jwtToken,
          ],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);
}

/// A class which mocks [LogInPageView].
///
/// See the documentation for Mockito's code generation for more information.
class MockLogInPageView extends _i1.Mock implements _i9.LogInPageView {
  MockLogInPageView() {
    _i1.throwOnMissingStub(this);
  }

  @override
  void setInProgress(bool? inProgress) => super.noSuchMethod(
        Invocation.method(
          #setInProgress,
          [inProgress],
        ),
        returnValueForMissingStub: null,
      );
  @override
  _i4.LogInFormView getLogInForm() => (super.noSuchMethod(
        Invocation.method(
          #getLogInForm,
          [],
        ),
        returnValue: _FakeLogInFormView_2(
          this,
          Invocation.method(
            #getLogInForm,
            [],
          ),
        ),
      ) as _i4.LogInFormView);
  @override
  void navigateToHome() => super.noSuchMethod(
        Invocation.method(
          #navigateToHome,
          [],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void notifyWrongCredentials() => super.noSuchMethod(
        Invocation.method(
          #notifyWrongCredentials,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [LogInFormView].
///
/// See the documentation for Mockito's code generation for more information.
class MockLogInFormView extends _i1.Mock implements _i4.LogInFormView {
  MockLogInFormView() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String getPassword() => (super.noSuchMethod(
        Invocation.method(
          #getPassword,
          [],
        ),
        returnValue: '',
      ) as String);
  @override
  String getEmail() => (super.noSuchMethod(
        Invocation.method(
          #getEmail,
          [],
        ),
        returnValue: '',
      ) as String);
  @override
  void clearForm() => super.noSuchMethod(
        Invocation.method(
          #clearForm,
          [],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void clearPassword() => super.noSuchMethod(
        Invocation.method(
          #clearPassword,
          [],
        ),
        returnValueForMissingStub: null,
      );
}
